package packet

import (
	"github.com/ubis/Freya/cmd/gameserver/def"
	"github.com/ubis/Freya/share/log"
	"github.com/ubis/Freya/share/script"
)

var g_ServerConfig = def.ServerConfig
var g_ServerSettings = def.ServerSettings
var g_PacketHandler = def.PacketHandler
var g_RPCHandler = def.RPCHandler
var g_NetworkManager = def.NetworkManager

// Registers network packets
func RegisterPackets() {
	log.Info("Registering packets...")

	var pk = g_PacketHandler
	pk.Register(GETMYCHARTR, "GetMyChartr", GetMyChartr)
	pk.Register(NEWMYCHARTR, "NewMyChartr", NewMyChartr)
	pk.Register(DELMYCHARTR, "DelMyChartr", DelMyChartr)
	pk.Register(CONNECT2SVR, "Connect2Svr", Connect2Svr)
	pk.Register(VERIFYLINKS, "VerifyLinks", VerifyLinks)
	pk.Register(INITIALIZED, "Initialized", Initialized)
	pk.Register(UNINITIALZE, "Uninitialze", Uninitialze)
	pk.Register(GETMYWAREHS, "GetMyWarehs", GetMyWarehs)
	pk.Register(QUICKLINKSET, "QuickLinkSet", QuickLinkSet)
	pk.Register(QUICKLINKSWAP, "QuickLinkSwap", QuickLinkSwap)
	pk.Register(GETSVRTIME, "GetSvrTime", GetSvrTime)
	pk.Register(ITEMLOOTING, "ItemLooting", ItemLooting)
	pk.Register(ITEMBUYINGS, "ItemBuyings", ItemBuyings)
	pk.Register(ITEMSELLING, "ItemSelling", ItemSelling)
	pk.Register(SKILLTOMOBS, "SkillToMobs", SkillToMobs)
	pk.Register(SKILLTOUSER, "SkillToUser", SkillToUser)
	pk.Register(COMBSKILSET, "ComboSkillSet", nil)
	pk.Register(REQ_COMBSKEVENT, "RequestComboSkillEvent", RequestComboSkillEvent)
	pk.Register(NFY_COMBSKEVENT, "NotifyComboSkillEvent", nil)
	pk.Register(SMASTUPEVNT, "StyleMasteryUpEvent", nil)
	pk.Register(ATTCKTOMOBS, "AttckToMobs", AttckToMobs)
	pk.Register(ATTCKTOUSER, "AttckToUser", AttckToUser)
	pk.Register(MOVEBEGINED, "MoveBegined", MoveBegined)
	pk.Register(MOVEENDED00, "MoveEnded", MoveEnded)
	pk.Register(MOVECHANGED, "MoveChanged", MoveChanged)
	pk.Register(MOVETILEPOS, "MoveTilePos", MoveTilePos)
	pk.Register(MESSAGEEVNT, "MessageEvnt", MessageEvnt)
	pk.Register(NEWUSERLIST, "NewUserList", nil)
	pk.Register(DELUSERLIST, "DelUserList", nil)
	pk.Register(NFY_ITEM_EQUIP, "NotifyItemEquip", nil)
	pk.Register(NFY_ITEM_UNEQUIP, "NotifyItemUnEquip", nil)
	pk.Register(NFY_NEWMOBSLIST, "NotifyNewMobsList", nil)
	pk.Register(NFY_DELMOBSLIST, "NotifyDelMobsList", nil)
	pk.Register(NFY_NEWITEMLIST, "NotifyNewItemList", nil)
	pk.Register(NFY_DELITEMLIST, "NotifyDelItemList", nil)
	pk.Register(NFY_MOVEBEGINED, "NotifyMoveBegined", nil)
	pk.Register(NFY_MOVEENDED00, "NotifyMoveEnded", nil)
	pk.Register(NFY_MOVECHANGED, "NotifyMoveChanged", nil)
	pk.Register(NFY_MOBSMOVEBGN, "NotifyMobsMoveBegin", nil)
	pk.Register(NFY_MOBSMOVEEND, "NotifyMobsMoveEnd", nil)
	pk.Register(NFY_MESSAGEEVNT, "NotifyMessageEvnt", nil)
	pk.Register(NFY_SKILLTOMOBS, "NotifySkillToMobs", nil)
	pk.Register(NFY_SKILLTOUSER, "NotifySkillToUser", nil)
	pk.Register(NFY_ATTCKTOMOBS, "NotifyAttckToMobs", nil)
	pk.Register(SYSTEMMESSG, "SystemMessg", nil)
	pk.Register(WARPCOMMAND, "WarpCommand", WarpCommand)
	pk.Register(USESTATBONS, "UseStatBons", UseStatBons)
	pk.Register(USERSTAT_AUTODISTRIBUTION, "UserStatAutoDistribution", UserStatAutoDistribution)
	pk.Register(ITEM_USING, "ItemUsing", ItemUsing)
	pk.Register(SKILLTOACTS, "SkillToActs", SkillToActs)
	pk.Register(NFY_SKILLTOACTS, "NotifySkillToActs", nil)
	pk.Register(CHANGESTYLE, "ChangeStyle", ChangeStyle)
	pk.Register(NFY_CHANGESTYLE, "NotifyChangeStyle", nil)
	pk.Register(CHARGEINFO, "ChargeInfo", ChargeInfo)
	pk.Register(PVP_REQUEST, "PVPRequest", PVPRequest)
	pk.Register(NFY_PVP_REQUEST, "NotifyPVPRequest", nil)
	pk.Register(PVP_RESPONSE, "PVPResponse", PVPResponse)
	pk.Register(NFY_PVP_RESPONSE, "NotifyPVPResponse", nil)
	pk.Register(PVP_PENDING, "PVPPending", PVPPending)
	pk.Register(NFY_PVP_PENDING, "NotifyPVPPending", nil)
	pk.Register(PVP_CANCEL, "PVPCancel", PVPCancel)
	pk.Register(NFY_PVP_CANCEL, "NotifyPVPCancel", nil)
	pk.Register(NFY_PVP_CHAR_INFO, "NotifyPVPCharInfo", nil)
	pk.Register(NEW_TARGET_USER, "NewTargetUser", NewTargetUser)
	pk.Register(END_TARGET_USER, "EndTargetUser", EndTargetUser)
	pk.Register(CHANGEDIRECTION, "ChangeDirection", ChangeDirection)
	pk.Register(REQ_BROADCAST, "RequestBroadcast", RequestBroadcast)
	pk.Register(NFY_CHANGEDIRECTION, "NotifyChangeDirection", nil)
	pk.Register(NFY_BROADCAST, "NotifyBroadcast", nil)
	pk.Register(KEYMOVEBEGINED, "KeyMoveBegined", KeyMoveBegined)
	pk.Register(KEYMOVEENDED00, "KeyMoveEnded", KeyMoveEnded)
	pk.Register(NFY_KEYMOVEBEGINED, "NotifyKeyMoveBegined", nil)
	pk.Register(NFY_KEYMOVEENDED00, "NotifyKeyMoveEnded", nil)
	pk.Register(KEYMOVECHANGED, "KeyMoveChanged", KeyMoveChanged)
	pk.Register(NFY_KEYMOVECHANGED, "NotifyKeyMoveChanged", nil)
	pk.Register(QUERYCASHITEM, "QueryCashItem", QueryCashItem)
	pk.Register(USECASHITEM, "UseCashItem", UseCashItem)
	pk.Register(SERVERENV, "ServerEnv", ServerEnv)
	pk.Register(ACCESSORY_EQUIP, "AccessoryEquip", AccessoryEquip)
	pk.Register(SKILLTOTARGET, "SkillToTarget", SkillToTarget)
	pk.Register(BUFFREMOVEBLESSSELF, "BuffRemoveBlessSelf", BuffRemoveBlessSelf)
	pk.Register(CHECK_USR_PDATA, "CheckUserPrivacyData", CheckUserPrivacyData)
	pk.Register(BACK_TO_CHAR_LOBBY, "BackToCharLobby", BackToCharLobby)
	pk.Register(SUBPW_SET, "SubPasswordSet", SubPasswordSet)
	pk.Register(SUBPW_CHECK_REQ, "SubPasswordCheckRequest", SubPasswordCheckRequest)
	pk.Register(SUBPW_CHECK, "SubPasswordCheck", SubPasswordCheck)
	pk.Register(SUBPW_FIND_REQ, "SubPasswordFindRequest", SubPasswordFindRequest)
	pk.Register(SUBPW_FIND, "SubPasswordFind", SubPasswordFind)
	pk.Register(SUBPW_DEL_REQ, "SubPasswordDelRequest", SubPasswordDelRequest)
	pk.Register(SUBPW_DEL, "SubPasswordDel", SubPasswordDel)
	pk.Register(SUBPW_CHG_QA_REQ,
		"SubPasswordChangeQARequest", SubPasswordChangeQARequest)
	pk.Register(SUBPW_CHG_QA, "SubPasswordChangeQA", SubPasswordChangeQA)
	pk.Register(SET_CHAR_SLOT_ORDER, "SetCharacterSlotOrder", SetCharacterSlotOrder)
	pk.Register(BUY_SKILL_BOOK, "BuySkillBook", BuySkillBook)
	pk.Register(UPGRADE_SKILL, "UpgradeSkill", UpgradeSkill)
	pk.Register(UNTRAIN_SKILL, "UntrainSkill", UntrainSkill)
	pk.Register(ENCHANT_CORE, "EnchantCore", EnchantCore)
	pk.Register(QUEST_OPEN, "QuestOpenEvent", QuestOpenEvent)
	pk.Register(QUEST_CLOSE, "QuestCloseEvent", QuestCloseEvent)
	pk.Register(QUEST_NPC_ACTION, "QuestNPCAction", QuestNPCAction)
	pk.Register(QUEST_UI_INFO, "QuestUIInfo", QuestUIInfo)
	pk.Register(UPGRADE_CORE_ENCHANT, "UpgradeCoreEnchant", UpgradeCoreEnchant)
	pk.Register(CHANNEL_LIST, "ChannelList", ChannelList)
	pk.Register(CHANNEL_CHANGE, "ChannelChange", ChannelChange)
	pk.Register(CHAR_DEL_CHK_SUBPW,
		"CharacterDeleteCheckSubPassword", CharacterDeleteCheckSubPassword)
	pk.Register(STORAGE_EXCHANGE_MOVE, "StorageExchangeMove", StorageExchangeMove)
	pk.Register(STORAGE_ITEM_SWAP, "StorageItemSwap", StorageItemSwap)
	pk.Register(STORAGE_ITEM_DROP, "StorageItemDrop", StorageItemDrop)
	pk.Register(ITEM_ATTACH, "ItemAttach", ItemAttach)
	pk.Register(NFY_RANKLIMITHOOK, "NotifyRankLimitHook", nil)
	pk.Register(UPDATE_HELPINFO, "UpdateHelpInfo", UpdateHelpInfo)
}

func RegisterFunc() {
	script.RegisterFunc("sendClientPacket", sessionPacketFunc{})
	script.RegisterFunc("sendClientMessage", clientMessageFunc{Fn: SendMessage})

	script.RegisterFunc("getPlayerLevel", playerGetLevelFunc{Fn: GetPlayerLevel})
	script.RegisterFunc("setPlayerLevel", playerSetLevelFunc{Fn: SetPlayerLevel})
	script.RegisterFunc("getPlayerPosition", playerPositionFunc{})
	script.RegisterFunc("dropItem", playerDropItemFunc{})
	script.RegisterFunc("addCashItem", playerAddCashItemFunc{})
}
